# Чтение из файла и запись в файл

In [9]:
import numpy as np

np.save('my_array',a)

np.savez('array.npz',a,b)

np.load('my_array.npy')

In [10]:
filename = 'array_t.txt'

In [11]:
data = np.loadtxt(filename,delimiter=',')

In [12]:
data

array([[  0.,   0.,   0.,   0.,   0.],
       [ 86.,  25.,  67.,  78.,   5.]])

In [15]:
def f(n,m):
    res = n + 10*m
    return res
A = np.fromfunction(f,(6,6),dtype=int);A

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55]])

In [20]:
np.savetxt("my_da.txt",A,delimiter=',')

In [21]:
A[:,1]

array([10, 11, 12, 13, 14, 15])

In [22]:
A[:,3]

array([30, 31, 32, 33, 34, 35])

In [23]:
A[:3,:3]

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22]])

# COPY
срез выбирает часть массива. можно изменить часть массива через срез