In [6]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a.shape

(3, 3)

In [10]:
a.ndim

2

In [11]:
len(a)

3

In [16]:
x = np.array([-1,0,1])
y = np.array([-2,0,3])

In [17]:
X,Y = np.meshgrid(x,y)

In [18]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [19]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 3,  3,  3]])

In [20]:
Z = (X+Y)**2
Z

array([[ 9,  4,  1],
       [ 1,  0,  1],
       [ 4,  9, 16]])

# Создание характерных массивов

In [21]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [27]:
a = np.full((2,3),7)
a

/Users/myomaung/anaconda/lib/python3.6/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 3), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 7.,  7.,  7.],
       [ 7.,  7.,  7.]])

In [28]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
np.eye(2,3,k=1)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [31]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1,10,0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9])

In [35]:
np.arange(2,10,dtype=np.int)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(2,10,dtype=np.float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [38]:
np.linspace(1.,4.,10)

array([ 1.        ,  1.33333333,  1.66666667,  2.        ,  2.33333333,
        2.66666667,  3.        ,  3.33333333,  3.66666667,  4.        ])

In [40]:
np.logspace(0,2,5)

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [41]:
f = np.indices((3,4))

In [42]:
f

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

# массив случайных чисел

In [43]:
np.random.random_sample()

0.13636575140263085

In [44]:
s = np.random.standard_normal((2,3))

In [45]:
s

array([[-0.40351077,  0.60932042, -1.18098568],
       [-0.69798374, -0.71563974,  1.05061976]])

In [46]:
np.random.randint(15)

3

In [47]:
np.random.randint(2,size=10)

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0])

In [48]:
np.random.randint(5,15,size=10)

array([ 8,  5,  8, 12,  7, 12, 11,  7, 13,  5])

In [49]:
np.random.randint(5,size=(2,4))

array([[3, 0, 0, 2],
       [0, 1, 1, 1]])

# Сделаем массив по формуле

In [51]:
def f(n,m):
    res = n + 10*m
    return res

In [53]:
A = np.fromfunction(f,(6,6),dtype=int);A

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55]])

# комплексные числа

In [54]:
d = np.array([1,2,3], dtype=complex);d

array([ 1.+0.j,  2.+0.j,  3.+0.j])