# Load in Numpy (remember to pip install numpy first)

In [30]:
import numpy as np

# The Basics

In [31]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [32]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [33]:
# Get dimension
a.ndim

1

In [34]:
b.ndim

2

In [35]:
# Get Shape
a.shape

(3,)

In [36]:
b.shape # 2 role, 3 columns

(2, 3)

# Accessing/Changing specific elements, rows, columns, etc

In [37]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
# Get a specific element [r,c]
a[1,5]

13

In [39]:
a[1,-2]

13

In [40]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [42]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [43]:
a[1,5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [44]:
a[:,2] = [10,20]
print (a)

[[ 1  2 10  4  5  6  7]
 [ 8  9 20 11 12 20 14]]


# 3D example

In [45]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Get specific element (work outside in)
b[0,1,1]

4

In [47]:
b[1,0,0]

5

In [48]:
b[0,1]

array([3, 4])

In [49]:
b[0,0,1]

2

In [59]:
# replace
b[:,1] = [[10,20],[30,40]]
b

array([[[ 1,  2],
        [10, 20]],

       [[ 5,  6],
        [30, 40]]])

In [67]:
b[:,0,:] = [[3,3],[1,5]]
b

array([[[ 3,  3],
        [10, 20]],

       [[ 1,  5],
        [30, 40]]])

# Initializing Different Types of Arrays

In [69]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [77]:
np.zeros((5,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [78]:
# All 1s matrix
np.ones((4,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [80]:
# Any other number
np.full((2,2),99, dtype='int32')

array([[99, 99],
       [99, 99]], dtype=int32)

In [82]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

# Random Integer values

In [85]:
np.random.randint(-4, 8, size=(4,3,4))

array([[[-4, -4,  2, -4],
        [ 0,  1, -2,  1],
        [ 0,  2,  6, -3]],

       [[ 2, -3, -2,  7],
        [ 2, -3,  1,  4],
        [ 1, -1,  3,  6]],

       [[-1,  3,  6,  7],
        [ 3,  1,  1,  7],
        [ 5,  7,  7,  5]],

       [[-2, -3,  6, -2],
        [-1,  4, -4, -2],
        [ 2,  3,  3,  6]]])

In [86]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print (r1)

[1 1 1 2 2 2 3 3 3]


In [88]:
arr

array([1, 2, 3])